-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM(p.price * o.sales_amount) AS SALES
FROM PRODUCT P, OFFLINE_SALE O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY product_code 
ORDER BY SALES DESC, P.PRODUCT_CODE ;