-- FAVORITES가 가장 많은 식당을 출력해야함
-- 방법 1 : GROUP 별로 랭크를 지정하고 
SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME,  A.FAVORITES
FROM (
    SELECT
    RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY favorites DESC ) AS RANK, REST_NAME, REST_ID, FAVORITES, FOOD_TYPE
    FROM REST_INFO) A
WHERE A.RANK = 1
ORDER BY FOOD_TYPE DESC
