SELECT M.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE,'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE M
JOIN REST_REVIEW R
ON M.MEMBER_ID = R.MEMBER_ID
JOIN (SELECT MEMBER_ID, RANK() OVER(ORDER BY COUNT(MEMBER_ID) DESC) AS RANK
     FROM REST_REVIEW
     GROUP BY MEMBER_ID) V
     ON R.MEMBER_ID = V.MEMBER_ID
WHERE V.RANK = 1
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT