-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(A.TOTAL_SALES)
FROM BOOK B
JOIN
(
SELECT book_id, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES 
WHERE TO_CHAR(SALES_DATE,'YYYYMM') LIKE '202201%'
GROUP BY book_id
) A
ON B.book_id = A.book_id
GROUP BY category
ORDER BY B.CATEGORY 

